### ISSUE TITLE
Docker execution sometimes truncates the leading portion of "_stdout"

### ISSUE THREAD

**Issue by brianhelba** [girder/girder_worker#187] opened 2017-09-07 00:27 UTC
To reproduce:
* Install and run girder_worker in Girder's Vagrant-managed VM
* Start Girder, build and enable item_tasks
* Install Docker, and build the item_tasks "demo" task:
    ```
    vagrant ssh
    sudo apt-get install docker-ce
    cd ~/girder/plugins/item_tasks/demo/
    docker build .
    ```
* Copy the Docker image ID of the resulting image
* Repeat these steps until failure (happens at least 50% of the time):
   * In Girder's web client, as an admin user, navigate to a new folder
   * Click `Folder actions` -> `Add tasks`
   * In the `JSON` tab, paste the new image ID into `Docker image identifier`, uncheck `Pull image from Docker Hub`
    * Click `Run` and watch as the task fails with a message like:
        ````
        HTTP push failed (http://localhost:8080/api/v1/folder/59b0381ab0e9570ae48699d5/item_task_json_specs). Response: {"message": "Invalid JSON passed in request body.", "type": "rest"}
        HTTPError: 400 Client Error: Bad Request for url: http://localhost:8080/api/v1/folder/59b0381ab0e9570ae48699d5/item_task_json_specs?image=1470ef21bba6&pullImage=False
        File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
            R = retval = fun(*args, **kwargs)
        File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
            return self.run(*args, **kwargs)
        File "/home/vagrant/girder_worker/girder_worker/tasks.py", line 19, in run
            return core.run(*pargs, **kwargs)
        File "/home/vagrant/girder_worker/girder_worker/core/utils.py", line 123, in wrapped
            return fn(*args, **kwargs)
        File "/home/vagrant/girder_worker/girder_worker/core/__init__.py", line 203, in run
            io.push(data, outputs[name], **dict({'task_output': task_output}, **kwargs))
        File "/home/vagrant/girder_worker/girder_worker/core/io/__init__.py", line 150, in push
            return _push_map[mode](data, spec, **kwargs)
        File "/home/vagrant/girder_worker/girder_worker/core/io/http.py", line 200, in push
            request.raise_for_status()
        File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
            raise HTTPError(http_error_msg, response=self)
        ````
* Using debugging tools, observe that the [value sent to the `_stdout` output (in the `data` parameter to `push`)](https://github.com/girder/girder_worker/blob/139d521589c08724e8f598ba82c52128042257a7/girder_worker/core/io/http.py#L193) is a string with only the very end of the JSONified demo task spec, with a leading portion truncated. For example:
    ```
         "description": "Choose a directory and name for an output folder",
                    "type": "new-folder",
                    "target": "filepath"
                }
            ]
        }
    ]
    ```

**Comment by brianhelba** [comment] 2017-09-07 00:29
@zachmullen Are you able to reproduce this, and do you have any idea what the problem is?

@sutartmelson , @jeffbaumes and I all witnessed this happening in my own Vagrant VM. At the time, it was failing almost 80% of the time.

**Comment by jbeezley** [comment] 2017-09-07 01:21
I think this was also happening for me this morning... I thought maybe I was hallucinating.

**Comment by cjh1** [comment] 2017-09-07 12:28
I can take a look at this, its probably related to docker-py's stream handling.

**Comment by cjh1** [comment] 2017-09-07 13:10
@brianhelba Are you install girder_worker from pypi? Looks like that version might not have fix I made a while back. Although its hard to tell as we don't seem to be tagging girder_worker releases.

**Comment by brianhelba** [comment] 2017-09-07 13:24
I'm running the latest master from yesterday.

**Comment by cjh1** [comment] 2017-09-07 13:26
Ok, I will try to recreate, thanks

**Comment by cjh1** [comment] 2017-09-08 20:01
Just a quick update, I am able to recreate this issue outside girder_worker with a docker-py script, will dig into what the issue is and raise the issue upstream is necessary.

**Comment by cjh1** [comment] 2017-11-02 12:55
I have pushed a patch upstream docker/docker-py#1788 that resolves this. When it makes it into a release I will bump our required version.

**Comment by cjh1** [comment] 2017-11-02 21:00
The upstream patch has been merged and should appear in a release in the next couple of weeks.

**Comment by cjh1** [comment] 2017-11-17 21:22
This upstream patch has now made it into a release: https://github.com/docker/docker-py/releases/tag/2.6.0, I will push our docker-py requirement  forward.

**Closed** 2017-11-29 01:16 UTC
