### ISSUE TITLE
Check if Celery Pinning is still necessary

### ISSUE THREAD

**Issue by kotfic** [girder/girder_worker#330] opened 2019-02-18 14:56 UTC
@manthey I seem to recall we pinned celery to `celery>=4,<4.2` because some of the things you were working on were having issues with connection pool dropping?  Do you think you could see if this is still an issue with 4.2.1?

**Comment by manthey** [comment] 2019-02-18 15:00
It looks like celery master has this fixed, but it is listed as targeted for v4.3 (https://github.com/celery/celery/issues/4867).

**Comment by danlamanna** [comment] 2019-02-18 17:57
I wouldn't expect a v4.3 release anytime soon, see https://github.com/celery/celery/issues/4957. In other projects I've just had to pick a sha from master and pin to it.

**Comment by danlamanna** [comment] 2019-02-26 19:22
Well that aged well: https://github.com/celery/celery/releases/tag/v4.3.0rc1.

**Comment by manthey** [comment] 2019-11-04 13:46
I've run into this problem again with celery 4.3.  It does seem resolved in 4.4.0rc3.  I think we should re-pin to celery <4.2 and >= 4.4.

**Comment by kotfic** [comment] 2019-11-07 14:43
@manthey are there any open issues to indicate other people are seeing the issue with 4.3?  I'd like to avoid pinning unless it's clear that 4.4 is going to fix a systemic problem with 4.3 related to connection pool dropping.

**Comment by manthey** [comment] 2019-11-07 14:55
The celery issue https://github.com/celery/celery/issues/4867 has several reports of this still being a problem in 4.3.

In working with slicer_cli_web and girder_worker, on celery 4.3.0 I get the problem "often" -- seemingly more than half the time I initiate a second job.  On celery 4.4.0rc3, I could not produce the problem.

We shouldn't have unpinned this without verifying that it was fixed -- I only didn't notice because the project I am using girder_worker on was using an older version where the pinned celery version was in place.

**Comment by kotfic** [comment] 2019-11-07 15:15
Is this an issue that can be resolved downstream at build/deploy time? I would be hesitant to forcibly revert celery versions across all downstream projects.

**Comment by manthey** [comment] 2019-11-07 16:09
celery 4.2 and 4.3 are broken using the rabbitmq broker.  We recommend rabbitmq in the readthedocs.  This would suggest either pinning celery or having a caveat about using rabbitmq in the docs.  I don't know what projects are using this successfully.  Are they using a different broker?

**Comment by kotfic** [comment] 2019-11-07 17:29
To be clear, Celery 4.2 and 4.3 - in conjunction with an unknown set of deployment configurations - are showing intermittent errors for _some_ users.  Until it is resolved in Celery, it should be mitigated in downstream projects that are experiencing the issue.

**Comment by manthey** [comment] 2019-11-07 18:23
Right.  Let's pin celery to mitigate the problem.

**Comment by manthey** [comment] 2019-11-07 18:25
Projects that somehow work despite the broken version of celery could override this -- our default installation should work rather than be broken.

**Comment by jbeezley** [comment] 2019-11-07 18:36
I don't know that I have followed this completely...  if I understand correctly, the problem is that if you pin celery here, you can't override it downstream.  When you try to import, python will throw a `VersionConflict` exception.

**Comment by zachmullen** [comment] 2019-11-07 18:49
I was reading the celery issue thread but not in super detail... is the issue in celery or kombu?

**Comment by kotfic** [comment] 2019-11-07 18:52
Its not clear what the issue is,  there is no consistently reproducible minimum working example of the error.

**Comment by zachmullen** [comment] 2019-11-07 18:56
https://python-rq.org/

🤷‍♂

**Comment by kotfic** [comment] 2019-11-07 19:07
@manthey Is there a practical reason this can't be mitigated downstream in your project code or is your concern more ideological?

**Comment by manthey** [comment] 2019-11-07 19:13
Of course it can be mitigated downstream.

I wasted quite a bit of time trying to figure out what was wrong with code when the problem was that girder_worker recommends a broken set of packages -- rabbitmq with current celery.  Unless we prevent it (by pinning celery), or advice against using rabbitmq (and have a working example of a different broker), anyone trying to use this project is doomed to sorrow and wasted time.  In trying to use the latest release of girder_worker, it works the first time and then fails "randomly".

**Comment by kotfic** [comment] 2019-11-08 13:55
I'm glad to hear that in the short term this can be mitigated downstream. Unless everyone else is secretly having this problem with Girder Worker and just not speaking up that's the fix until 4.4.0 is released.  

Can I get some feedback from @girder/developers  as to whether this widely observed behavior?

**Comment by zachmullen** [comment] 2019-11-08 14:10
I haven't seen it, though to be fair I'm not currently administering lots of G_W jobs in the wild.

I'm on board with not trying to fix this here given that we don't actually even know where the problem is.

**Comment by zachmullen** [comment] 2019-11-08 14:13
> girder_worker recommends a broken set of packages

Earlier in the thread it was mentioned that this couldn't be minimally reproduced, is that not the case? If such a repro exists I could be persuaded that it's appropriate to try to fix this in g_worker.

**Comment by danlamanna** [comment] 2019-11-08 15:10
I'm not using girder-worker, but anecdotally I've been running Celery 4.3.0 with RabbitMQ on multiple projects for several months without running into this issue.

For what it's worth, overly specific pinning has caused my downstream projects a lot of pain in the past since it's more likely to lead to an unresolvable set of packages.

**Comment by manthey** [comment] 2019-11-08 15:32
It is useful to know that Celery 4.3 (particularly via girder_worker) is being used successfully with RabbitMQ.  I'll make a PR for adding to the documentation to the effect of "if you see this problem, try this".

**Comment by zachmullen** [comment] 2019-11-08 15:41
Great, thanks @manthey

**Comment by manthey** [comment] 2024-01-10 17:55
This was resolved quite some time ago.

**Closed by manthey** 2024-01-10 17:55 UTC
